### PR TITLE
fix TFO a bug and updata all packet

### PR DESCRIPTION
**Pull request by ghost**
It will  improve performance

### CODE REVIEW

**Comment by Potterli20** [comment]
Can use back to https://github.com/database64128/tfo-go??
His long time no update https://github.com/SagerNet/tfo-go at a time
可以用回https://github.com/database64128/tfo-go？？
他那个好久更新一次https://github.com/SagerNet/tfo-go

**Comment by Potterli20** [comment]
dialer_sing_box "github.com/sagernet/sing-box/common/dialer"
	"github.com/sagernet/sing/common/metadata"
	"github.com/database64128/tfo-go/v2"
	
	Could it?

**Comment by lbsystem** [comment]
The library at `http://github.com/database64128/tfo-go/v2` is designed for listeners, making applications more stable and faster. However, singbox's TFO is more closely integrated with TLS.




------------------ Original ------------------
From: trli ***@***.***&gt;
Date: Tue,Mar 26,2024 7:15 PM
To: p4gefau1t/trojan-go ***@***.***&gt;
Cc: lbsystem ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [p4gefau1t/trojan-go] fix TFO a bug and updata all packet (PR#528)





 dialer_sing_box "github.com/sagernet/sing-box/common/dialer" "github.com/sagernet/sing/common/metadata" "github.com/database64128/tfo-go/v2" Could it?

**Comment by ghost** [comment]
The library at `http://github.com/database64128/tfo-go/v2` is designed for listeners, making applications more stable and faster. However, singbox's TFO is more closely integrated with TLS.

Next time, I anticipate improving the response time when using TLS 1.2 by adopting session tickets. In the future, if Go supports TLS 1.3 0-RTT, I will follow up with that as well.
Singbox's TFO has been conducting user authentication for TLS for a long time, so using Singbox's TFO as a client is more prudent.


------------------ Original ------------------
From: trli ***@***.***&gt;
Date: Tue,Mar 26,2024 7:15 PM
To: p4gefau1t/trojan-go ***@***.***&gt;
Cc: lbsystem ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [p4gefau1t/trojan-go] fix TFO a bug and updata all packet (PR#528)





 dialer_sing_box "github.com/sagernet/sing-box/common/dialer" "github.com/sagernet/sing/common/metadata" "github.com/database64128/tfo-go/v2" Could it?

**Comment by Potterli20** [comment]
> The library at `http://github.com/database64128/tfo-go/v2` is designed for listeners, making applications more stable and faster. However, singbox's TFO is more closely integrated with TLS. Next time, I anticipate improving the response time when using TLS 1.2 by adopting session tickets. In the future, if Go supports TLS 1.3 0-RTT, I will follow up with that as well.
> […](#)
> ------------------ Original ------------------ From: trli ***@***.***&gt; Date: Tue,Mar 26,2024 7:15 PM To: p4gefau1t/trojan-go ***@***.***&gt; Cc: lbsystem ***@***.***&gt;, Author ***@***.***&gt; Subject: Re: [p4gefau1t/trojan-go] fix TFO a bug and updata all packet (PR#528) dialer_sing_box "github.com/sagernet/sing-box/common/dialer" "github.com/sagernet/sing/common/metadata" "github.com/database64128/tfo-go/v2" Could it? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

okok，I suggest fork trojan-go-fork, and then update, and can you help me repair clinet's ws protocol, thank you!!

**Pull request closed without merging**
